/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ['selector', '[data-codenote-theme="dark"]'],
    content: ['./src/**/*.{ts,tsx}'],
    prefix: 'codenote__',
    theme: {
        container: {
            center: true,
            padding: '32px',
            screens: {
                '2xl': '1400px',
            },
        },
        extend: {
            colors: {
                border: 'hsla(var(--border))',
                input: 'hsla(var(--input))',
                ring: 'hsla(var(--ring))',
                background: 'hsla(var(--background))',
                foreground: 'hsla(var(--foreground))',
                primary: {
                    DEFAULT: 'hsla(var(--primary))',
                    foreground: 'hsla(var(--primary-foreground))',
                },
                secondary: {
                    DEFAULT: 'hsla(var(--secondary))',
                    foreground: 'hsla(var(--secondary-foreground))',
                },
                destructive: {
                    DEFAULT: 'hsla(var(--destructive))',
                    foreground: 'hsla(var(--destructive-foreground))',
                },
                muted: {
                    DEFAULT: 'hsla(var(--muted))',
                    foreground: 'hsla(var(--muted-foreground))',
                },
                accent: {
                    DEFAULT: 'hsla(var(--accent))',
                    foreground: 'hsla(var(--accent-foreground))',
                },
                popover: {
                    DEFAULT: 'hsla(var(--popover))',
                    foreground: 'hsla(var(--popover-foreground))',
                },
                card: {
                    DEFAULT: 'hsla(var(--card))',
                    foreground: 'hsla(var(--card-foreground))',
                },
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
            },
            keyframes: {
                'accordion-down': {
                    from: { height: '0' },
                    to: { height: 'var(--radix-accordion-content-height)' },
                },
                'accordion-up': {
                    from: { height: 'var(--radix-accordion-content-height)' },
                    to: { height: '0' },
                },
            },
            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up': 'accordion-up 0.2s ease-out',
            },
            spacing: {
                0: '0px',
                0.5: '2px',
                1: '4px',
                1.5: '6px',
                2: '8px',
                2.5: '10px',
                3: '12px',
                3.5: '14px',
                4: '16px',
                5: '20px',
                6: '24px',
                7: '28px',
                8: '32px',
                9: '36px',
                10: '40px',
                11: '44px',
                12: '48px',
                14: '56px',
                16: '64px',
                20: '80px',
                24: '96px',
                28: '112px',
                32: '128px',
                36: '144px',
                40: '160px',
                44: '176px',
                48: '192px',
                52: '208px',
                56: '224px',
                60: '240px',
                64: '256px',
                72: '288px',
                80: '320px',
                96: '384px',
            },
            fontSize: {
                xxs: '10px',
                xs: '12px',
                sm: '14px',
                base: '16px',
                lg: '18px',
                xl: '20px',
            },
        },
    },
    plugins: [require('tailwindcss-animate')],
};
